### ISSUE TITLE
Compiling error with compiling Mqtt.h library

### ISSUE THREAD

**Issue by GulzaibKhan-BSEE17021** [ubidots/ubidots-particle-mqtt#11]
Hey there. my problem is that when compiling my code for esp32-mqtt.h file on arduino, the compiling error of MQTT.h: No such file or directory exists appears. Even though I have imported the required libraries from Github to Arduino IDE. Can anyone help me solve this issue;(

**Comment by jotathebest** [comment]
This library is intended to be used by devices manufactured by Particle, not by Espressif.

Closing
