### ISSUE TITLE
MQTT/MQTT.h: No such file or directory

### ISSUE THREAD

**Issue by jade7272** [ubidots/ubidots-particle-mqtt#2]
Veryfing code using this library in Particle Build fails with this error:

```
UbidotsMQTT/UbidotsMQTT.h:29:23: fatal error: MQTT/MQTT.h: No such file or directory
 #include "MQTT/MQTT.h"
                       ^
```

**Comment by Metavix** [comment]
@jade7272 the reason of that error is because you need to add mqtt lib. Follow the  steps of readme. There, we explain how to do that and the requirements
